FROM ubuntu:22.04

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get update && apt-get install -y --no-install-recommends \
    pdftk imagemagick libimage-exiftool-perl xpdf make \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
